name: Build Geode Mod

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Clean Environment and Extract Files
      run: |
        mkdir temp_extract
        unzip -q *.zip -d temp_extract
        find temp_extract -name "mod.json" -exec dirname {} \; | head -n 1 > target_dir.txt
        TARGET=$(cat target_dir.txt)
        mv "$TARGET"/* .
        rm -rf temp_extract target_dir.txt *.zip

    - name: Build Mod File
      uses: geode-sdk/build-geode-mod@main
      with:
        target: iOS
