name: Build Geode Mod

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Unzip Mod Files
      run: |
        unzip "MultiplayerEditor-main.zip" -d temp_folder
        if [ -d "temp_folder/MultiplayerEditor-main" ]; then
          mv temp_folder/MultiplayerEditor-main/* .
        elif [ -d "temp_folder/MultiplayerEditor" ]; then
          mv temp_folder/MultiplayerEditor/* .
        else
          mv temp_folder/* .
        fi
        rm -rf temp_folder "MultiplayerEditor-main.zip"

    - name: Build Mod File
      uses: geode-sdk/build-geode-mod@main
